name: hw1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: ^0.14.3
  flutter_swipe_action_cell: ^3.1.5
  http: ^1.3.0
  path_provider: ^2.1.5
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/MontserratFont/static/Montserrat-SemiBold.ttf
        - asset: assets/fonts/MontserratFont/static/Montserrat-Bold.ttf
  assets:
    - assets/icons/icon.png
    - assets/images/placeholder.png
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#9C27B0"
  adaptive_icon_foreground: "assets/icons/icon.png"